# coding: utf-8

"""
    Server API

    Reference for Server API (REST/Json)

    OpenAPI spec version: 2.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.apis.product_accesses_api import ProductAccessesApi


class TestProductAccessesApi(unittest.TestCase):
    """ ProductAccessesApi unit test stubs """

    def setUp(self):
        self.api = kinow_client.apis.product_accesses_api.ProductAccessesApi()

    def tearDown(self):
        pass

    def test_create_product_access(self):
        """
        Test case for create_product_access

        
        """
        pass

    def test_delete_product_access(self):
        """
        Test case for delete_product_access

        
        """
        pass

    def test_get_customer_accesses_subscriptions(self):
        """
        Test case for get_customer_accesses_subscriptions

        
        """
        pass

    def test_get_customer_accesses_videos(self):
        """
        Test case for get_customer_accesses_videos

        
        """
        pass

    def test_get_product_access(self):
        """
        Test case for get_product_access

        
        """
        pass

    def test_get_product_accesses(self):
        """
        Test case for get_product_accesses

        
        """
        pass

    def test_subscribe(self):
        """
        Test case for subscribe

        
        """
        pass

    def test_switch_subscription(self):
        """
        Test case for switch_subscription

        
        """
        pass

    def test_switch_subscription_delete(self):
        """
        Test case for switch_subscription_delete

        
        """
        pass

    def test_switch_subscription_pending(self):
        """
        Test case for switch_subscription_pending

        
        """
        pass

    def test_unsubscribe(self):
        """
        Test case for unsubscribe

        
        """
        pass

    def test_update_product_access(self):
        """
        Test case for update_product_access

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
