# coding: utf-8

"""
    Kinow API

    Client API for Kinow back-office

    OpenAPI spec version: 1.4.26
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.apis.pages_api import PagesApi


class TestPagesApi(unittest.TestCase):
    """ PagesApi unit test stubs """

    def setUp(self):
        self.api = kinow_client.apis.pages_api.PagesApi()

    def tearDown(self):
        pass

    def test_get_page(self):
        """
        Test case for get_page

        
        """
        pass

    def test_get_pages(self):
        """
        Test case for get_pages

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
