# coding: utf-8

"""
    Kinow API

    Client API for Kinow back-office

    OpenAPI spec version: 1.4.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.models.prepayment_bonus_1 import PrepaymentBonus1


class TestPrepaymentBonus1(unittest.TestCase):
    """ PrepaymentBonus1 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrepaymentBonus1(self):
        """
        Test PrepaymentBonus1
        """
        model = kinow_client.models.prepayment_bonus_1.PrepaymentBonus1()


if __name__ == '__main__':
    unittest.main()
