# coding: utf-8

"""
    Kinow API

    Client API for Kinow back-office

    OpenAPI spec version: 1.4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.models.video_group_1 import VideoGroup1


class TestVideoGroup1(unittest.TestCase):
    """ VideoGroup1 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVideoGroup1(self):
        """
        Test VideoGroup1
        """
        model = kinow_client.models.video_group_1.VideoGroup1()


if __name__ == '__main__':
    unittest.main()
