# coding: utf-8

"""
    Server API

    Reference for Server API (REST/Json)

    OpenAPI spec version: 1.4.51
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.apis.cms_pages_api import CMSPagesApi


class TestCMSPagesApi(unittest.TestCase):
    """ CMSPagesApi unit test stubs """

    def setUp(self):
        self.api = kinow_client.apis.cms_pages_api.CMSPagesApi()

    def tearDown(self):
        pass

    def test_create_cms_page(self):
        """
        Test case for create_cms_page

        
        """
        pass

    def test_get_cms_pages(self):
        """
        Test case for get_cms_pages

        
        """
        pass

    def test_update_cms_page(self):
        """
        Test case for update_cms_page

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
