# coding: utf-8

"""
    Server API

    Reference for Server API (REST/Json)

    OpenAPI spec version: 2.0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.models.cart_price_request import CartPriceRequest


class TestCartPriceRequest(unittest.TestCase):
    """ CartPriceRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCartPriceRequest(self):
        """
        Test CartPriceRequest
        """
        model = kinow_client.models.cart_price_request.CartPriceRequest()


if __name__ == '__main__':
    unittest.main()
