# coding: utf-8

"""
    Kinow API

    Client API for Kinow Rest API

    OpenAPI spec version: 1.4.32
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.apis.cms_categories_api import CMSCategoriesApi


class TestCMSCategoriesApi(unittest.TestCase):
    """ CMSCategoriesApi unit test stubs """

    def setUp(self):
        self.api = kinow_client.apis.cms_categories_api.CMSCategoriesApi()

    def tearDown(self):
        pass

    def test_create_cms_category(self):
        """
        Test case for create_cms_category

        
        """
        pass

    def test_get_cms_categories(self):
        """
        Test case for get_cms_categories

        
        """
        pass

    def test_update_cms_category(self):
        """
        Test case for update_cms_category

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
