# coding: utf-8

"""
    Kinow API

    Client API for Kinow Rest API

    OpenAPI spec version: 1.4.34
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.apis.attributes_api import AttributesApi


class TestAttributesApi(unittest.TestCase):
    """ AttributesApi unit test stubs """

    def setUp(self):
        self.api = kinow_client.apis.attributes_api.AttributesApi()

    def tearDown(self):
        pass

    def test_create_product_attribute(self):
        """
        Test case for create_product_attribute

        
        """
        pass

    def test_delete_attribute(self):
        """
        Test case for delete_attribute

        
        """
        pass

    def test_get_product_attributes(self):
        """
        Test case for get_product_attributes

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
