# coding: utf-8

"""
    Kinow API

    Client API for Kinow back-office

    OpenAPI spec version: 1.3.73
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kinow_client
from kinow_client.rest import ApiException
from kinow_client.models.videos_2 import Videos2


class TestVideos2(unittest.TestCase):
    """ Videos2 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVideos2(self):
        """
        Test Videos2
        """
        model = kinow_client.models.videos_2.Videos2()


if __name__ == '__main__':
    unittest.main()
