# coding: utf-8

"""
    Kaemo API

    Public api for Kaemo back office

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import kaemo_client
from kaemo_client.rest import ApiException
from kaemo_client.models.order_histories import OrderHistories


class TestOrderHistories(unittest.TestCase):
    """ OrderHistories unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderHistories(self):
        """
        Test OrderHistories
        """
        model = kaemo_client.models.order_histories.OrderHistories()


if __name__ == '__main__':
    unittest.main()
