# coding: utf-8

"""
    Kaemo API

    Public api for Kaemo back office

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.access import Access
from .models.address import Address
from .models.cart import Cart
from .models.cart_body import CartBody
from .models.cart_rule import CartRule
from .models.cart_rules import CartRules
from .models.countries import Countries
from .models.country import Country
from .models.currencies import Currencies
from .models.currency import Currency
from .models.customer import Customer
from .models.customers import Customers
from .models.feature import Feature
from .models.feature_value import FeatureValue
from .models.features import Features
from .models.gender import Gender
from .models.genders import Genders
from .models.geoloc import Geoloc
from .models.geolocs import Geolocs
from .models.i18n_field import I18nField
from .models.language import Language
from .models.languages import Languages
from .models.media_file import MediaFile
from .models.media_files import MediaFiles
from .models.media_source import MediaSource
from .models.media_sources import MediaSources
from .models.o_auth_token import OAuthToken
from .models.order import Order
from .models.order_histories import OrderHistories
from .models.order_history import OrderHistory
from .models.order_state import OrderState
from .models.order_states import OrderStates
from .models.orders import Orders
from .models.pagination import Pagination
from .models.payment_module import PaymentModule
from .models.payment_modules import PaymentModules
from .models.payment_url import PaymentUrl
from .models.product import Product
from .models.product_access import ProductAccess
from .models.product_attribute import ProductAttribute
from .models.product_attributes_response import ProductAttributesResponse
from .models.products import Products
from .models.subscription import Subscription
from .models.subscription_accesses import SubscriptionAccesses
from .models.subscriptions import Subscriptions
from .models.video import Video
from .models.video_url import VideoUrl
from .models.videos import Videos

# import apis into sdk package
from .apis.accesses_api import AccessesApi
from .apis.address_api import AddressApi
from .apis.attributes_api import AttributesApi
from .apis.cart_rules_api import CartRulesApi
from .apis.carts_api import CartsApi
from .apis.countries_api import CountriesApi
from .apis.currencies_api import CurrenciesApi
from .apis.customers_api import CustomersApi
from .apis.features_api import FeaturesApi
from .apis.genders_api import GendersApi
from .apis.geolocations_api import GeolocationsApi
from .apis.languages_api import LanguagesApi
from .apis.media_files_api import MediaFilesApi
from .apis.media_sources_api import MediaSourcesApi
from .apis.o_auth_api import OAuthApi
from .apis.order_histories_api import OrderHistoriesApi
from .apis.order_states_api import OrderStatesApi
from .apis.orders_api import OrdersApi
from .apis.payment_modules_api import PaymentModulesApi
from .apis.product_accesses_api import ProductAccessesApi
from .apis.products_api import ProductsApi
from .apis.subscriptions_api import SubscriptionsApi
from .apis.videos_api import VideosApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
